source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftFileManager_Example', :exclusive => true do
  pod "SwiftFileManager", :path => "../"
end

target 'SwiftFileManager_Tests', :exclusive => true do
  pod "SwiftFileManager", :path => "../"

  
end
